//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.M.S_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public int product { get; set; }
        public int quantity { get; set; }
        public double cost { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual product product1 { get; set; }
    }
}
